### ISSUE TITLE
Reassign main and focus._id to match point._id

### ISSUE THREAD

**Issue by josephmturner** [USHIN-Inc/ushin-db#6]
SemanticScreen component sets main and focus._id  to each match one of the point._ids stored in points. Because PouchDB reassigns assigns every single point._id but leaves main and focus._id alone, main and focus do not refer to the correct points. In fact, they do not refer to any point._id stored in PouchDB.

My attempt at resolving this bug:
https://github.com/josephmturner/ushin-db/tree/reassign_main

**Comment by RangerMauve** [comment]
The bug that was causing this was fixed here: https://github.com/USHIN-Inc/ushin-db/commit/4eeddbb0e04bfab0829eabf8181aa3f914ae5d43

IDs no longer get reassigned if they're provided by the semscreen
